---
language: python

matrix:
  exclude:
    - python: pypy
      env: LMDB_FORCE_CPYTHON=1
    - python: pypy
      env: LMDB_FORCE_CPYTHON=1 LMDB_PURE=1
    - python: pypy3
      env: LMDB_FORCE_CPYTHON=1
    - python: pypy3
      env: LMDB_FORCE_CPYTHON=1 LMDB_PURE=1

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy
  # - pypy3
  # - nightly

env:
  - LMDB_FORCE_CFFI=1
  - LMDB_FORCE_CPYTHON=1
  - LMDB_FORCE_CFFI=1 LMDB_PURE=1
  - LMDB_FORCE_CPYTHON=1 LMDB_PURE=1
install:
  - sudo apt-get install gdb
  - pip install cffi

  - python setup.py develop
before_script:
  - source misc/helpers.sh

script:
  - >
    with_gdb python -m pytest tests

notifications:
  email: false
